version: '3.10'

services:
  app:
    build:
      context: .
      # Args is given here to install req.dev.txt file only for dev enviroment
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
