---
name: Checks

on: [push] # Trigger our job when code is pushed

jobs: 
  test-lint: # Id of our job
    name: Test and Lint # The user-friendly name of our job
    runs-on: ubuntu-20.04 # The os on which the job will run on
    steps:
      - name: Login to Docker Hub  # Human readable name of our step
        uses: docker/login-action@v1 # It uses the premade action provided in the GitHub actions repo
        with:
          username: ${{ secrets.DOCKERHUB_USER }} # Reads the username and token stored in our secrets of our repo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"